# DVF clean

#### Import

In [1]:
import pandas as pd

In [75]:
data = pd.read_csv("data/stats_dvf.csv")

#### lookup

In [76]:
data.describe()

,nb_ventes_maison,moy_prix_m2_maison,med_prix_m2_maison,nb_ventes_appartement,moy_prix_m2_appartement,med_prix_m2_appartement,nb_ventes_local,moy_prix_m2_local,med_prix_m2_local,nb_ventes_apt_maison,moy_prix_m2_apt_maison,med_prix_m2_apt_maison
count,2.960606e+06,2.960606e+06,2.960606e+06,1.159277e+06,1.159277e+06,1.159277e+06,250347.000000,250347.000000,250347.000000,3.651209e+06,3.651209e+06,3.651209e+06
mean,4.475905e+00,2.373033e+03,2.362131e+03,9.954140e+00,3.548511e+03,3.531435e+03,5.376585,2238.974100,2175.657088,6.789804e+00,2.636182e+03,2.620854e+03
std,2.159976e+02,1.918971e+03,1.902421e+03,3.221247e+02,2.598543e+03,2.593751e+03,145.084735,3285.693569,3251.564304,3.739723e+02,2.131060e+03,2.115869e+03
min,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,1.000000,0.000000,0.000000,1.000000e+00,0.000000e+00,0.000000e+00
25%,1.000000e+00,1.324000e+03,1.317000e+03,1.000000e+00,1.940000e+03,1.920000e+03,1.000000,629.000000,598.000000,1.000000e+00,1.415000e+03,1.405000e+03
50%,1.000000e+00,1.990000e+03,1.988000e+03,2.000000e+00,2.967000e+03,2.949000e+03,1.000000,1371.000000,1308.000000,1.000000e+00,2.145000e+03,2.138000e+03
75%,2.000000e+00,2.912000e+03,2.907000e+03,3.000000e+00,4.309000e+03,4.294000e+03,2.000000,2670.000000,2582.000000,2.000000e+00,3.235000e+03,3.220000e+03
max,8.178900e+04,9.992000e+04,9.992000e+04,6.659000e+04,9.878100e+04,9.878100e+04,15769.000000,98885.000000,98885.000000,1.483790e+05,9.992000e+04,9.992000e+04

In [77]:
data.shape

(3651209, 17)

In [79]:
data.head()

,code_geo,nb_ventes_maison,moy_prix_m2_maison,med_prix_m2_maison,nb_ventes_appartement,moy_prix_m2_appartement,med_prix_m2_appartement,nb_ventes_local,moy_prix_m2_local,med_prix_m2_local,nb_ventes_apt_maison,moy_prix_m2_apt_maison,med_prix_m2_apt_maison,annee_mois,libelle_geo,code_parent,echelle_geo
0,01,453.0,2431.0,2177.0,275.0,2827.0,2417.0,24.0,1260.0,779.0,728,2581,2214,2021-01,Ain,nation,departement
1,01,442.0,2397.0,2128.0,220.0,3131.0,2333.0,29.0,977.0,689.0,662,2641,2202,2021-02,Ain,nation,departement
2,01,498.0,2449.0,2203.0,279.0,2749.0,2400.0,44.0,1182.0,959.0,777,2557,2241,2021-03,Ain,nation,departement
3,01,507.0,2509.0,2292.0,320.0,2944.0,2564.0,29.0,1555.0,920.0,827,2678,2349,2021-04,Ain,nation,departement
4,01,470.0,2560.0,2327.0,334.0,3068.0,2757.0,41.0,1040.0,795.0,804,2771,2428,2021-05,Ain,nation,departement

#### quick clean

In [83]:
data = data.drop(columns=["code_parent", "echelle_geo", "nb_ventes_local", "moy_prix_m2_local", "med_prix_m2_local"])

In [85]:
data.columns

Index(['code_geo', 'nb_ventes_maison', 'moy_prix_m2_maison',
       'med_prix_m2_maison', 'nb_ventes_appartement',
       'moy_prix_m2_appartement', 'med_prix_m2_appartement',
       'nb_ventes_apt_maison', 'moy_prix_m2_apt_maison',
       'med_prix_m2_apt_maison', 'annee_mois', 'libelle_geo'],
      dtype='str')

#### Real data cleaning/organisation

In [295]:
paris_data = data[data["code_geo"] == "75"]
paris_data["annee_mois"] = pd.to_datetime(paris_data["annee_mois"])
paris_data["mois"] = paris_data["annee_mois"].dt.month 
paris_data = paris_data.sort_values("annee_mois")

paris_all_data = paris_data[["code_geo", "nb_ventes_apt_maison","moy_prix_m2_apt_maison", "med_prix_m2_apt_maison", "libelle_geo", "annee_mois", "mois"]]
paris_all_data["taux de variation"] = paris_all_data["moy_prix_m2_apt_maison"].pct_change()
paris_all_data.head()

,code_geo,nb_ventes_apt_maison,moy_prix_m2_apt_maison,med_prix_m2_apt_maison,libelle_geo,annee_mois,mois,taux de variation
629244,75,2166,11004,10902,Paris,2021-01-01,1,NaN
629245,75,2161,10834,10800,Paris,2021-02-01,2,-0.015449
629246,75,2697,10665,10682,Paris,2021-03-01,3,-0.015599
629247,75,2473,10745,10717,Paris,2021-04-01,4,0.007501
629248,75,2562,10793,10769,Paris,2021-05-01,5,0.004467

In [304]:
paris_maison_data = paris_data[["code_geo", "nb_ventes_maison","moy_prix_m2_maison", "med_prix_m2_maison", "libelle_geo", "annee_mois", "mois"]]
paris_maison_data["taux de variation"] = paris_maison_data["moy_prix_m2_maison"].pct_change()
paris_maison_data.head()

,code_geo,nb_ventes_maison,moy_prix_m2_maison,med_prix_m2_maison,libelle_geo,annee_mois,mois,taux de variation
629244,75,8.0,15106.0,13647.0,Paris,2021-01-01,1,NaN
629245,75,9.0,10902.0,11953.0,Paris,2021-02-01,2,-0.278300
629246,75,18.0,19529.0,17737.0,Paris,2021-03-01,3,0.791323
629247,75,12.0,13184.0,12070.0,Paris,2021-04-01,4,-0.324901
629248,75,15.0,16626.0,15830.0,Paris,2021-05-01,5,0.261074

In [309]:
paris_appartement_data = paris_data[["code_geo", "nb_ventes_appartement","moy_prix_m2_appartement", "med_prix_m2_appartement", "libelle_geo", "annee_mois", "mois"]]
paris_appartement_data["taux de variation"] = paris_appartement_data["moy_prix_m2_appartement"].pct_change()
paris_appartement_data = paris_appartement_data.dropna(subset=['taux de variation'])
paris_appartement_data.head()

,code_geo,nb_ventes_appartement,moy_prix_m2_appartement,med_prix_m2_appartement,libelle_geo,annee_mois,mois,taux de variation
629245,75,2152.0,10834.0,10800.0,Paris,2021-02-01,2,-0.014105
629246,75,2679.0,10605.0,10667.0,Paris,2021-03-01,3,-0.021137
629247,75,2461.0,10733.0,10716.0,Paris,2021-04-01,4,0.012070
629248,75,2547.0,10758.0,10745.0,Paris,2021-05-01,5,0.002329
629249,75,3324.0,10897.0,10840.0,Paris,2021-06-01,6,0.012921

> sensitivity is too high due to few transactions for Paris house market. Thus we will only focus on appartment

#### final results

In [313]:
r_month = paris_appartement_data["taux de variation"].mean()
sigma_month = paris_appartement_data["taux de variation"].std()

print(r_month, sigma_month)

-0.001040650324210819 0.01963991829264719